"""Keep a long-running Streamlit process on this checkout's source generation."""

import hashlib
import importlib
from pathlib import Path
import sys
from threading import RLock

_LOCK = RLock()


def source_signature(package: Path) -> str:
    """Match btc_analyzer's import-time signature, independent of mtimes/pyc."""
    digest = hashlib.sha256()
    for path in sorted(package.rglob("*.py")):
        digest.update(path.relative_to(package).as_posix().encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def ensure_checkout(root: Path) -> str:
    """Reload our package only after a source change, legacy load or wrong origin.

    An ordinary rerun keeps the same modules/classes and expensive data caches.
    No private visitor records or third-party modules are removed.
    """
    source = root.resolve() / "src"
    package = source / "btc_analyzer"
    with _LOCK:
        sys.path[:] = [str(source), *[path for path in sys.path if path != str(source)]]
        expected = source_signature(package)
        loaded = {
            name: module
            for name, module in sys.modules.copy().items()
            if name == "btc_analyzer" or name.startswith("btc_analyzer.")
        }
        parent = loaded.get("btc_analyzer")
        matching = (
            parent is not None
            and getattr(parent, "__checkout_signature__", None) == expected
            and Path(getattr(parent, "__file__", "")).resolve() == package / "__init__.py"
        )
        # A watcher can evict a parent while an older child survives. In
        # particular, old candles.py lacks the newly deployed boundary helper.
        candles = loaded.get("btc_analyzer.candles")
        matching = matching and (candles is None or hasattr(candles, "candle_boundary"))
        matching = matching and all(
            Path(module.__file__).resolve().is_relative_to(package)
            for module in loaded.values()
            if getattr(module, "__file__", None)
        )
        if matching:
            return expected
        # Also cover a watcher evicting every module before the next run.
        # Git updates can preserve pyc timestamps/sizes by chance; only this
        # checkout's generated bytecode is disposable, never third-party files.
        for cached in package.rglob("__pycache__/*.pyc"):
            try:
                cached.unlink(missing_ok=True)
            except OSError:
                pass
        for name in loaded:
            sys.modules.pop(name, None)
        streamlit = sys.modules.get("streamlit")
        if streamlit is not None:
            streamlit.cache_data.clear()
        importlib.invalidate_caches()
        current = importlib.import_module("btc_analyzer")
        return current.__checkout_signature__
