[server]
headless = true
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false
maxUploadSize = 1
maxMessageSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3182F6"
backgroundColor = "#F5F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#191F28"
